package io.semanticdf.mcp.handlers

import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers._

/** Tests for the `introspect` tool's pure-function helpers — the
  * `parseInventory` and `parseWarnings` YAML parsers. The actual
  * `Introspector.fromFile` Spark call is exercised by the library's own
  * tests; we don't need to round-trip a real file here.
  *
  * We also test the request-shape parser via `Introspect.parseRequest`
  * (which takes the SDK's `Map[String, Object]`). */
class IntrospectSpec extends AnyFunSuite {

  // ---------------------------------------------------------------------------
  // (1) parseInventory — counts from a representative Introspector YAML
  // ---------------------------------------------------------------------------

  test("parseInventory counts dimensions, measures, and skipped fields from a typical Introspector YAML") {
    val yaml =
      """# Auto-generated by semanticdf introspector.
        |# 1000 rows, 5 columns.
        |# Edit before using in production — this is a starter, not a final model.
        |
        |orders:
        |  table: <source name>
        |  description: "Auto-generated from orders — review and edit"
        |
        |  dimensions:
        |    customer_id:
        |      expr: customer_id
        |      is_entity: true
        |    order_date:
        |      expr: order_date
        |      is_time_dimension: true
        |    region:
        |      expr: region
        |      metadata:
        |        tags: [geo]
        |
        |  measures:
        |    order_count:
        |      expr: "count(1)"
        |    total_amount:
        |      expr: "sum(amount)"
        |
        |  joins:
        |    customer_id_to_customers:
        |      left_on: customer_id
        |      right_on: id
        |""".stripMargin

    val inv = Introspect.parseInventory(yaml)
    inv.dimensions shouldBe 3
    inv.measures   shouldBe 2
    inv.skipped    shouldBe 0   // 5 total = 3 dims + 2 measures
  }

  test("parseInventory accounts for joins section (entity columns not in dimensions)") {
    val yaml =
      """# Auto-generated.
        |# 100 rows, 4 columns.
        |
        |flights:
        |  table: foo
        |
        |  dimensions:
        |    carrier:
        |      expr: carrier
        |    origin:
        |      expr: origin
        |
        |  measures:
        |    flight_count:
        |      expr: "count(1)"
        |
        |  joins:
        |    customer_id_to_customers:
        |      left_on: customer_id
        |      right_on: id
        |""".stripMargin

    val inv = Introspect.parseInventory(yaml)
    inv.dimensions shouldBe 2   // only the two in `dimensions:` (carrier, origin)
    inv.measures   shouldBe 1
    inv.skipped    shouldBe 0   // 4 total - 2 dims - 1 measure - 1 join = 0 (all classified)
  }

  test("parseInventory returns zeros when no header is present (malformed YAML)") {
    val yaml =
      """orders:
        |  dimensions:
        |    carrier:
        |      expr: carrier
        |""".stripMargin
    val inv = Introspect.parseInventory(yaml)
    inv.dimensions shouldBe 1
    inv.measures   shouldBe 0
    inv.skipped    shouldBe 0   // totalCols is 0 (no header), so skipped clamps to 0
  }

  test("parseInventory returns zeros on empty input") {
    val inv = Introspect.parseInventory("")
    inv.dimensions shouldBe 0
    inv.measures   shouldBe 0
    inv.skipped    shouldBe 0
  }

  // ---------------------------------------------------------------------------
  // (2) parseWarnings — currently empty (Introspector doesn't emit them)
  // ---------------------------------------------------------------------------

  test("parseWarnings returns empty for any YAML (library doesn't emit warnings yet)") {
    Introspect.parseWarnings("anything") shouldBe empty
  }

  // ---------------------------------------------------------------------------
  // (3) parseRequest — SDK Map → Request DTO
  // ---------------------------------------------------------------------------

  test("parseRequest returns Some for all keys when the agent supplies the optional fields") {
    import scala.jdk.CollectionConverters._
    val options: java.util.Map[String, String] = Map("mergeSchema" -> "true").asJava
    val scalaMap: Map[String, AnyRef] = Map[String, AnyRef](
      "table"        -> "orders",
      "format"       -> "parquet",
      "path"         -> "/data/orders.parquet",
      "model_name"   -> "orders",
      "read_options" -> options,
    )
    val args: java.util.Map[String, Object] = scalaMap.asJava

    val req = Introspect.parseRequest(args)
    req.table        shouldBe Some("orders")
    req.format       shouldBe Some("parquet")
    req.path         shouldBe Some("/data/orders.parquet")
    req.model_name   shouldBe Some("orders")
    req.read_options shouldBe Map("mergeSchema" -> "true")
  }

  test("parseRequest returns None for missing fields and an empty read_options map") {
    import scala.jdk.CollectionConverters._
    val args: java.util.Map[String, Object] = Map.empty[String, AnyRef].asJava

    val req = Introspect.parseRequest(args)
    req.table        shouldBe None
    req.format       shouldBe None
    req.path         shouldBe None
    req.model_name   shouldBe None
    req.read_options shouldBe empty
  }
}
