package io.semanticdf.tools

import org.apache.spark.sql.{DataFrame, SparkSession, Row}
import org.apache.spark.sql.types._
import scala.util.matching.Regex

/** Auto-generate a starter YAML model from a DataFrame schema + sample rows.
  *
  * The hardest part of writing a YAML model is the FIRST one. Once a user
  * sees what an inferred model looks like, they can edit and refine. This
  * introspector produces a sensible starter, not the final model.
  *
  * Heuristics:
  *   - StringType       → dimension
  *   - BooleanType      → dimension
  *   - DateType / TimestampType → dimension + is_time_dimension=true
  *   - NumericType (int/long) → measure (sum, count, avg)
  *   - NumericType (double/float) → measure (sum, avg)
  *   - Column name == "id" / "*_id" / "*_key" → entity dimension
  *   - Column name matches PII patterns (email/ssn/phone/name) → pii metadata
  *   - Column name has "code" / "type" / "status" → identifier metadata
  *
  * Usage:
  * {{{
  *   val introspector = new Introspector()
  *   val df = spark.read.parquet("/path/to/data")
  *   val yaml = introspector.toYaml(df, modelName = "orders")
  *   println(yaml)
  * }}}
  *
  * @param config Configuration knobs (max measures, etc.)
  */
class Introspector(config: Introspector.Config = Introspector.Config()) {

  /** Per-call configuration. */
  def withConfig(c: Introspector.Config): Introspector = new Introspector(c)
  def withMaxMeasures(n: Int): Introspector = withConfig(config.copy(maxMeasures = n))
  def withSampleSize(n: Int): Introspector = withConfig(config.copy(sampleSize = n))

  /** Read a file (parquet, csv, json) and return the inferred YAML.
    *
    * @param path   Path to the data file/directory
    * @param format "parquet", "csv", "json", or any Spark read format
    *               (with optional options as a Map)
    * @param modelName  The model name to use in the YAML
    */
  def fromFile(spark: SparkSession,
               path: String,
               format: String = "parquet",
               modelName: String,
               readOptions: Map[String, String] = Map.empty): String = {
    val reader = spark.read.format(format).options(readOptions)
    val df = format match {
      case "csv"    => reader.option("header", "true").option("inferSchema", "true").csv(path)
      case "json"   => reader.option("inferSchema", "true").json(path)
      case "parquet" => reader.parquet(path)
      case other    => reader.load(path)
    }
    toYaml(df, modelName)
  }

  /** Inspect a DataFrame and return a YAML model definition string.
    *
    * @param df          The DataFrame to introspect
    * @param modelName   The model name (used as the YAML top-level key)
    */
  def toYaml(df: DataFrame, modelName: String): String = {
    require(modelName.trim.nonEmpty, "model name must be non-blank")
    val schema    = df.schema
    val fields    = schema.fields.toSeq
    val nRows     = safeCount(df)
    val sample    = takeSample(df, config.sampleSize)
    val fieldInfo = fields.map(f => Introspector.FieldInfo.from(f, sample))

    val dimFields = fieldInfo.filter(_.suggestAsDimension)
    val measureCandidates = fieldInfo.filter(!_.suggestAsDimension)
    val pickedMeasures = pickMeasures(measureCandidates, config.maxMeasures)
    val joinFields      = pickJoins(fieldInfo)

    val dimensions = dimFields.map(_.toDimensionYaml)
    val measures   = pickedMeasures.map(_.toMeasureYaml)
    val joins      = joinFields.map(_.toJoinYaml)

    // Skipped fields: anything not picked as a dimension, measure, or join.
    // Each skipped field gets a # WARN: line in the YAML header so the
    // MCP `introspect` tool can surface it via `response.warnings`.
    // Two reasons a field is skipped:
    //   1. measure candidate that didn't make the top maxMeasures
    //   2. no dimension/measure classification (e.g. opaque blob columns)
    val pickedNames = (
      dimFields.map(_.name) ++
      pickedMeasures.map(_.name) ++
      joinFields.map(_.name)
    ).toSet
    val skipped = fieldInfo.filterNot(f => pickedNames.contains(f.name))

    val sb = new StringBuilder
    sb.append(s"# Auto-generated by semanticdf introspector.\n")
    sb.append(s"# $nRows rows, ${fields.length} columns.\n")
    sb.append(s"# Edit before using in production — this is a starter, not a final model.\n")
    skipped.foreach { f =>
      val reason =
        if (f.suggestedMeasureKind.isDefined) "max measures limit reached"
        else "no dimension or measure classification"
      sb.append(s"# WARN: field '${f.name}' (${f.dataType.typeName}) was skipped — $reason\n")
    }
    sb.append(s"\n")
    sb.append(s"$modelName:\n")
    sb.append(s"  table: <source name>  # ← change this to your actual table/file\n")
    sb.append(s"  description: \"Auto-generated from ${modelName} — review and edit\"\n")

    if (dimensions.nonEmpty) {
      sb.append(s"\n  dimensions:\n")
      dimensions.foreach(d => sb.append(d))
    } else {
      sb.append(s"\n  # (no dimensions inferred — your data has only numeric columns)\n")
    }

    if (measures.nonEmpty) {
      sb.append(s"\n  measures:\n")
      measures.foreach(m => sb.append(m))
    } else {
      sb.append(s"\n  # (no measures inferred — your data has only categorical columns)\n")
    }

    if (joins.nonEmpty) {
      sb.append(s"\n  joins:\n")
      joins.foreach(j => sb.append(j))
    }

    sb.toString
  }

  /** Pick the measures to emit. We limit to `maxMeasures` to avoid generating
    * 50+ measures for very wide tables (most of which the user won't want). */
  private def pickMeasures(candidates: Seq[Introspector.FieldInfo], maxMeasures: Int): Seq[Introspector.FieldInfo] = {
    // Priority order: counts/sums first, then averages, then others
    val priority: Seq[Introspector.FieldInfo] = candidates.sortBy { (f: Introspector.FieldInfo) =>
      val kind = f.suggestedMeasureKind.getOrElse("other")
      kind match {
        case "count"   => 0
        case "sum"     => 1
        case "avg"     => 2
        case _         => 3
      }
    }
    priority.take(maxMeasures)
  }

  /** Pick candidate join keys (columns ending in _id, _key, etc.). Emits
    * placeholder joins for each — user must define the target model. */
  private def pickJoins(fields: Seq[Introspector.FieldInfo]): Seq[Introspector.FieldInfo] = {
    fields.filter(_.isEntity)
  }

  /** Safe count that doesn't fail on empty/invalid data. */
  private def safeCount(df: DataFrame): Long =
    try df.count() catch { case _: Throwable => -1L }

  /** Take up to `n` sample rows for type inference verification. */
  private def takeSample(df: DataFrame, n: Int): Array[Row] =
    try df.limit(n).collect() catch { case _: Throwable => Array.empty }
}

object Introspector {

  /** Configuration for an introspector run. */
  case class Config(
    /** Maximum number of measures to emit. Default 8. */
    maxMeasures: Int = 8,
    /** Number of rows to sample for type verification. Default 100. */
    sampleSize: Int = 100,
  )

  /** Information inferred about a single field. */
  case class FieldInfo(
    name: String,
    dataType: DataType,
    nullable: Boolean,
    distinctSampleRatio: Double,    // 0.0..1.0
    sampleValues: Seq[Any],
    suggestAsDimension: Boolean,
    isEntity: Boolean,
    isTimeDimension: Boolean,
    pii: Boolean,
    suggestedMeasureKind: Option[String],
    suggestedExpr: Option[String],
    metadata: Map[String, String],
  ) {
    /** Render this field as a YAML dimension block. */
    def toDimensionYaml: String = {
      val sb = new StringBuilder
      sb.append(s"    $name:\n")
      sb.append(s"      expr: $name\n")
      if (isTimeDimension) sb.append(s"      is_time_dimension: true\n")
      val md = metadata.map { case (k, v) => s"        $k: $v" }.mkString("\n")
      if (md.nonEmpty) sb.append(s"      metadata:\n$md\n")
      sb.toString
    }

    /** Render this field as a YAML measure block. */
    def toMeasureYaml: String = {
      val sb = new StringBuilder
      val kind = suggestedMeasureKind.getOrElse("sum")
      sb.append(s"    $name:\n")
      sb.append(s"      expr: \"${suggestedExpr.getOrElse(s"$kind($name)")}\"\n")
      val md = metadata.map { case (k, v) => s"        $k: $v" }.mkString("\n")
      if (md.nonEmpty) sb.append(s"      metadata:\n$md\n")
      sb.toString
    }

    /** Render this field as a YAML join placeholder. */
    def toJoinYaml: String = {
      val sb = new StringBuilder
      sb.append(s"    ${Introspector.FieldInfo.joinAlias(name)}_model:  # ← adjust the alias and target\n")
      sb.append(s"      model: <target-model-name>\n")
      sb.append(s"      type: many\n")
      sb.append(s"      left_on: $name\n")
      sb.append(s"      right_on: <target-key>\n")
      sb.toString
    }
  }

  object FieldInfo {

    /** PII patterns: column names that suggest personal/sensitive data. */
    val PiiPatterns: Seq[Regex] = Seq(
      "(?i).*email.*".r,
      "(?i).*phone.*".r,
      "(?i).*ssn.*".r,
      "(?i).*password.*".r,
      "(?i).*address.*".r,
      "(?i).*first_?name.*".r,
      "(?i).*last_?name.*".r,
      "(?i).*full_?name.*".r,
    )

    /** Patterns for join-key / entity columns. */
    val EntityPatterns: Seq[Regex] = Seq(
      "(?i)^id$".r,
      "(?i).*_id$".r,
      "(?i).*_key$".r,
      "(?i)^.*_uuid$".r,
      "(?i).*code$".r,
    )

    /** Entity suffixes, longest-first, used by [[joinAlias]] to derive
      * a clean placeholder alias from a column name. e.g. `customer_id`
      * → `customer` (drops `_id`), `event_uuid` → `event` (drops `_uuid`).
      * Kept in sync with [[EntityPatterns]]: every pattern that ends in
      * `_xxx` should appear here. The bare `^id$` pattern has no suffix
      * to drop (handled in [[joinAlias]]). */
    private val EntitySuffixes: Seq[String] = Seq(
      "_uuid",
      "_code",
      "_key",
      "_id",
    )

    /** Derive a placeholder alias from a column name. Drops a recognised
      * entity suffix (`_id`, `_key`, `_uuid`, `_code`) and any trailing
      * underscore the suffix left behind. Falls back to the column name
      * itself if no entity suffix is present (so bare `id` → `id`,
      * `customer_id` → `customer`, `order_id` → `order`,
      * `event_uuid` → `event`, `airline_code` → `airline`).
      *
      * The result is meant to be a readable placeholder; the user is
      * expected to adjust it to match their target model name. */
    def joinAlias(name: String): String = {
      val lower = name.toLowerCase
      EntitySuffixes.find(lower.endsWith) match {
        case Some(suffix) =>
          val stripped = name.dropRight(suffix.length)
          if (stripped.endsWith("_")) stripped.dropRight(1) else stripped
        case None =>
          // Bare `id` (no underscore) — keep the column name as-is so the
          // placeholder becomes `id_model`, not `_model`.
          name
      }
    }

    /** Patterns for time-dimension columns. */
    val TimePatterns: Seq[Regex] = Seq(
      "(?i)^.*_at$".r,                    // created_at, updated_at
      "(?i)^.*_date$".r,
      "(?i)^.*_time$".r,
      "(?i)^.*_timestamp$".r,
      "(?i)^date$".r,
      "(?i)^time$".r,
      "(?i)^timestamp$".r,
    )

    def from(field: StructField, sample: Array[Row]): FieldInfo = {
      val name      = field.name
      val dataType  = field.dataType
      val nullable  = field.nullable
      val distinct   = if (sample.isEmpty) 0.0 else sample.map(_.getAs[Any](field.name)).distinct.length.toDouble / sample.length
      val values    = if (sample.isEmpty) Seq.empty[Any] else sample.map(_.getAs[Any](field.name)).filter(_ != null).take(5).toSeq
      val isPii     = PiiPatterns.exists(_.findFirstIn(name).isDefined)
      val isEntity  = EntityPatterns.exists(_.findFirstIn(name).isDefined)
      val isTime    = TimePatterns.exists(_.findFirstIn(name).isDefined) ||
                       dataType == DateType || dataType == TimestampType

      val (asDim, measureKind, measureExpr) = classifyField(name, dataType, isTime)

      val metadata = scala.collection.mutable.Map[String, String]()
      if (isEntity) metadata("tags") = "identifier"
      if (isPii)    metadata("pii") = "true"
      if (isTime)   metadata("unit") = "timestamp"
      metadata("owner") = "data-platform-team"

      FieldInfo(
        name = name,
        dataType = dataType,
        nullable = nullable,
        distinctSampleRatio = distinct,
        sampleValues = values,
        suggestAsDimension = asDim,
        isEntity = isEntity,
        isTimeDimension = isTime,
        pii = isPii,
        suggestedMeasureKind = measureKind,
        suggestedExpr = measureExpr,
        metadata = metadata.toMap,
      )
    }

    /** Decide: is this field a dimension, measure, or both? */
    private def classifyField(name: String, dataType: DataType, isTime: Boolean):
        (Boolean, Option[String], Option[String]) = {
      dataType match {
        case StringType =>
          // PII strings are NEVER measures
          val isPiiName = PiiPatterns.exists(_.findFirstIn(name).isDefined)
          (true, None, None)
        case BooleanType =>
          (true, None, None)
        case _: DateType if isTime =>
          (true, None, None)
        case _: TimestampType if isTime =>
          (true, None, None)
        case _: NumericType =>
          // Numeric → measure. Skip if the column name is suspicious for measures
          // (e.g. "year" is sometimes numeric but really a time grain).
          (false, numericMeasureKind(name, dataType), numericMeasureExpr(name, dataType))
        case _ =>
          // Unknown / struct / array — skip
          (false, None, None)
      }
    }

    /** For numeric columns: count? sum? avg? Depends on cardinality hint. */
    private def numericMeasureKind(name: String, dt: DataType): Option[String] = {
      // For low-cardinality numeric (looks like a category), avg makes more sense than sum.
      // For high-cardinality numeric, sum or avg.
      val n = name.toLowerCase
      if (n.contains("count") || n.contains("qty") || n.contains("amount") || n.contains("price") ||
          n.contains("revenue") || n.contains("cost") || n.contains("total"))
        Some("sum")
      else if (dt == DoubleType || dt == FloatType)
        Some("avg")
      else
        Some("sum")
    }

    private def numericMeasureExpr(name: String, dt: DataType): Option[String] = {
      // Choose a Spark SQL aggregate that fits.
      val n = name.toLowerCase
      val kind = numericMeasureKind(name, dt).getOrElse("sum")
      Some(s"$kind($name)")
    }
  }
}
